begin;

alter table products
    add column if not exists product_id bigint generated by default as identity;

create unique index if not exists products_product_id_key
    on products (product_id);

alter table tickets
    add column if not exists product_id bigint;

create index if not exists tickets_product_id_idx
    on tickets (product_id);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'tickets_product_id_fk'
          and conrelid = 'tickets'::regclass
    ) then
        alter table tickets
            add constraint tickets_product_id_fk
            foreign key (product_id) references products(product_id)
            on delete restrict on update restrict
            not valid;
    end if;
end;
$$;

commit;